import 'dart:ui';
import 'dart:io';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'package:record/record.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:uuid/uuid.dart';

import '../services/auth_service.dart';
import '../theme/app_colors.dart';
import '../theme/app_spacing.dart';
import '../widgets/avatar_widget.dart';
import '../models/message_model.dart';
import '../widgets/message_bubble.dart';
import '../widgets/date_group_header.dart';
import '../widgets/message_action_sheet.dart';

class ChatDetailScreen extends StatefulWidget {
  final String chatId;
  final String targetUserName;
  final String targetUserId;

  const ChatDetailScreen({
    super.key,
    required this.chatId,
    required this.targetUserName,
    required this.targetUserId,
  });

  @override
  State<ChatDetailScreen> createState() => _ChatDetailScreenState();
}

class _ChatDetailScreenState extends State<ChatDetailScreen> {
  final TextEditingController _messageController = TextEditingController();
  final ScrollController _scrollController = ScrollController();
  
  MessageModel? _replyingTo;
  MessageModel? _editingMessage;
  bool _isTyping = false;
  
  // Audio recording
  late final AudioRecorder _audioRecorder;
  bool _isRecording = false;
  DateTime? _recordingStartTime;

  @override
  void initState() {
    super.initState();
    _audioRecorder = AudioRecorder();
    _messageController.addListener(() {
      final isTyping = _messageController.text.trim().isNotEmpty;
      if (isTyping != _isTyping) {
        setState(() => _isTyping = isTyping);
      }
    });
  }

  @override
  void dispose() {
    _messageController.dispose();
    _scrollController.dispose();
    _audioRecorder.dispose();
    super.dispose();
  }

  Future<void> _sendMessage({
    String? text,
    String? mediaUrl,
    MediaType mediaType = MediaType.none,
    int? audioDuration,
  }) async {
    final user = context.read<AuthService>().currentUser;
    if (user == null) return;

    final actualText = text ?? _messageController.text.trim();
    if (actualText.isEmpty && mediaUrl == null) return;

    _messageController.clear();
    final replyId = _replyingTo?.id;
    final editingId = _editingMessage?.id;
    setState(() {
      _replyingTo = null;
      _editingMessage = null;
    });

    try {
      final messagesRef = FirebaseFirestore.instance
          .collection('chats')
          .doc(widget.chatId)
          .collection('messages');

      final chatDocRef = FirebaseFirestore.instance.collection('chats').doc(widget.chatId);

      // Update conversation metadata
      String lastMessage = actualText;
      if (lastMessage.isEmpty) {
        if (mediaType == MediaType.image) lastMessage = '📷 Photo';
        if (mediaType == MediaType.audio) lastMessage = '🎵 Voice note';
      }

      await chatDocRef.set({
        'participants': [user.id, widget.targetUserId],
        'lastMessage': lastMessage,
        'lastUpdated': FieldValue.serverTimestamp(),
        'participantNames': FieldValue.arrayUnion([user.fullName, widget.targetUserName]),
      }, SetOptions(merge: true));

      if (editingId != null) {
        // Edit existing message
        await messagesRef.doc(editingId).update({
          'text': actualText,
          'isEdited': true,
        });
      } else {
        // Send new message
        final newMessage = MessageModel(
          id: '', // Generated by Firestore
          senderId: user.id,
          senderName: user.fullName,
          text: actualText,
          replyTo: replyId,
          mediaUrl: mediaUrl,
          mediaType: mediaType,
          audioDuration: audioDuration,
        );

        await messagesRef.add(newMessage.toMap());
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to send: $e')));
      }
    }
  }

  Future<void> _pickImage() async {
    final picker = ImagePicker();
    // Use low quality to ensure it fits within Firestore's 1MB limit
    final pickedFile = await picker.pickImage(source: ImageSource.gallery, imageQuality: 30);
    if (pickedFile == null) return;

    try {
      final file = File(pickedFile.path);
      final bytes = await file.readAsBytes();
      final base64String = base64Encode(bytes);
      
      // Firestore has a hard limit of 1 MiB per document (approx 1,048,576 bytes)
      if (base64String.length > 900000) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Image is too large for Firestore. Try a smaller image.')));
        }
        return;
      }
      
      await _sendMessage(mediaUrl: base64String, mediaType: MediaType.image);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to process image: $e')));
      }
    }
  }

  Future<void> _startRecording() async {
    final status = await Permission.microphone.request();
    if (status != PermissionStatus.granted) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text("Microphone permission required")));
      }
      return;
    }

    final directory = await getApplicationDocumentsDirectory();
    final path = '${directory.path}/${const Uuid().v4()}.m4a';

    await _audioRecorder.start(
      const RecordConfig(encoder: AudioEncoder.aacLc, bitRate: 128000),
      path: path,
    );
    setState(() {
      _isRecording = true;
      _recordingStartTime = DateTime.now();
    });
  }

  Future<void> _stopRecording() async {
    final path = await _audioRecorder.stop();
    setState(() {
      _isRecording = false;
    });

    if (path == null) return;
    final file = File(path);
    
    // Calculate rough duration
    final duration = _recordingStartTime != null ? DateTime.now().difference(_recordingStartTime!).inMilliseconds : 0;
    
    // Ignore recordings < 1 second
    if (duration < 1000) return;

    try {
      final bytes = await file.readAsBytes();
      final base64String = base64Encode(bytes);
      
      if (base64String.length > 900000) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Voice note is too long for Firestore (Limit: ~1MB)')));
        }
        return;
      }

      await _sendMessage(mediaUrl: base64String, mediaType: MediaType.audio, audioDuration: duration);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Failed to process audio: $e')));
      }
    }
  }

  void _markAsRead(String messageId) {
    FirebaseFirestore.instance
        .collection('chats')
        .doc(widget.chatId)
        .collection('messages')
        .doc(messageId)
        .update({'read': true});
  }

  void _showActionSheet(MessageModel message, bool isMine) {
    showModalBottomSheet(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (context) => MessageActionSheet(
        message: message,
        isMine: isMine,
        onReact: (emoji) async {
          try {
            final user = context.read<AuthService>().currentUser;
            if (user == null) return;
            
            final reactions = Map<String, List<String>>.from(message.reactions);
            
            // Remove user from any existing reaction first
            reactions.forEach((key, list) {
              list.remove(user.id);
            });
            
            // Add to new reaction
            if (!reactions.containsKey(emoji)) {
              reactions[emoji] = [];
            }
            reactions[emoji]!.add(user.id);
            
            await FirebaseFirestore.instance
                .collection('chats')
                .doc(widget.chatId)
                .collection('messages')
                .doc(message.id)
                .update({'reactions': reactions});
          } catch (e) {
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Reaction failed: $e')));
            }
          }
        },
        onReply: () {
          setState(() => _replyingTo = message);
        },
        onEdit: () {
          setState(() {
            _editingMessage = message;
            _messageController.text = message.text;
          });
        },
        onCopy: () {
          // Add clipboard support here if needed
        },
        onDelete: () async {
          try {
            // Delete the message
            await FirebaseFirestore.instance
                .collection('chats')
                .doc(widget.chatId)
                .collection('messages')
                .doc(message.id)
                .delete();
                
            // Update the last message in the chat metadata
            final latestMsgs = await FirebaseFirestore.instance
                .collection('chats')
                .doc(widget.chatId)
                .collection('messages')
                .orderBy('timestamp', descending: true)
                .limit(1)
                .get();
                
            String newLastMessage = "";
            if (latestMsgs.docs.isNotEmpty) {
              final lastDoc = latestMsgs.docs.first.data();
              newLastMessage = lastDoc['text'] ?? '';
              if (newLastMessage.isEmpty) {
                if (lastDoc['mediaType'] == 'image') newLastMessage = '📷 Photo';
                else if (lastDoc['mediaType'] == 'audio') newLastMessage = '🎵 Voice note';
              }
            } else {
              newLastMessage = "No messages";
            }
            
            await FirebaseFirestore.instance
                .collection('chats')
                .doc(widget.chatId)
                .update({'lastMessage': newLastMessage});
                
          } catch (e) {
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Delete failed: $e')));
            }
          }
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = context.read<AuthService>().currentUser;
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: Row(
          children: [
            AvatarWidget(
              userId: widget.targetUserId,
              name: widget.targetUserName,
              radius: 18,
            ),
            const SizedBox(width: AppSpacing.md),
            Text(widget.targetUserName),
          ],
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance
                  .collection('chats')
                  .doc(widget.chatId)
                  .collection('messages')
                  .orderBy('timestamp', descending: true)
                  .snapshots(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }
                if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
                  return Center(
                    child: Text(
                      "Start the conversation",
                      style: TextStyle(
                        color: isDark ? AppColors.darkTextSecondary : AppColors.lightTextSecondary,
                      ),
                    ),
                  );
                }

                final docs = snapshot.data!.docs;
                final messages = docs.map((d) => MessageModel.fromMap(d.data() as Map<String, dynamic>, d.id)).toList();
                final messageMap = {for (var m in messages) m.id: m};

                return ListView.builder(
                  reverse: true,
                  controller: _scrollController,
                  padding: const EdgeInsets.symmetric(vertical: AppSpacing.lg),
                  itemCount: messages.length,
                  itemBuilder: (context, index) {
                    final message = messages[index];
                    final bool isMine = message.senderId == user?.id;

                    // Mark as read if it's from the other person and unread
                    if (!isMine && !message.read && message.id.isNotEmpty) {
                      WidgetsBinding.instance.addPostFrameCallback((_) {
                        _markAsRead(message.id);
                      });
                    }

                    // Date grouping logic
                    bool showDateHeader = false;
                    if (index == messages.length - 1) {
                      showDateHeader = true; // Oldest message
                    } else if (message.timestamp != null) {
                      final prevMessage = messages[index + 1];
                      if (prevMessage.timestamp != null) {
                        final currentDay = DateTime(message.timestamp!.year, message.timestamp!.month, message.timestamp!.day);
                        final prevDay = DateTime(prevMessage.timestamp!.year, prevMessage.timestamp!.month, prevMessage.timestamp!.day);
                        if (currentDay != prevDay) {
                          showDateHeader = true;
                        }
                      }
                    }

                    return Column(
                      children: [
                        if (showDateHeader && message.timestamp != null)
                          DateGroupHeader(date: message.timestamp!),
                        MessageBubble(
                          message: message,
                          isMine: isMine,
                          replyMessage: message.replyTo != null ? messageMap[message.replyTo!] : null,
                          onLongPress: () => _showActionSheet(message, isMine),
                        ),
                      ],
                    );
                  },
                );
              },
            ),
          ),
          
          // Reply/Edit Preview
          if (_replyingTo != null || _editingMessage != null)
            Container(
              margin: const EdgeInsets.symmetric(horizontal: AppSpacing.md, vertical: 4),
              padding: const EdgeInsets.all(AppSpacing.sm),
              decoration: BoxDecoration(
                color: isDark ? AppColors.darkSurface : AppColors.lightSurface,
                borderRadius: BorderRadius.circular(AppSpacing.radiusMd),
                border: Border.all(
                  color: isDark ? AppColors.darkBorder : AppColors.lightBorder,
                ),
              ),
              child: Row(
                children: [
                  Container(
                    width: 4,
                    height: 40,
                    margin: const EdgeInsets.only(right: 8),
                    decoration: BoxDecoration(
                      color: theme.colorScheme.primary,
                      borderRadius: BorderRadius.circular(2),
                    ),
                  ),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          _editingMessage != null ? 'Editing Message' : _replyingTo!.senderName,
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            color: theme.colorScheme.primary,
                            fontSize: 12,
                          ),
                        ),
                        Text(
                          _editingMessage != null
                              ? 'Edit your message below'
                              : (_replyingTo!.text.isNotEmpty ? _replyingTo!.text : (_replyingTo!.mediaType.toString())),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            color: isDark ? AppColors.darkTextSecondary : AppColors.lightTextSecondary,
                            fontSize: 12,
                          ),
                        ),
                      ],
                    ),
                  ),
                  IconButton(
                    icon: const Icon(Icons.close, size: 20),
                    onPressed: () {
                      setState(() {
                        _replyingTo = null;
                        _editingMessage = null;
                        _messageController.clear();
                      });
                    },
                  ),
                ],
              ),
            ),
          
          // Input Area
          SafeArea(
            child: Container(
              padding: const EdgeInsets.symmetric(horizontal: AppSpacing.md, vertical: AppSpacing.sm),
              decoration: BoxDecoration(
                color: isDark ? AppColors.darkSurface.withValues(alpha: 0.9) : AppColors.lightSurface.withValues(alpha: 0.9),
              ),
              child: Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.add_a_photo),
                    color: theme.colorScheme.primary,
                    onPressed: _pickImage,
                  ),
                  Expanded(
                    child: Container(
                      decoration: BoxDecoration(
                        color: isDark ? Colors.black.withValues(alpha: 0.2) : Colors.black.withValues(alpha: 0.05),
                        borderRadius: BorderRadius.circular(AppSpacing.radiusPill),
                      ),
                      child: TextField(
                        controller: _messageController,
                        maxLines: 5,
                        minLines: 1,
                        textInputAction: TextInputAction.send,
                        onSubmitted: (_) => _sendMessage(),
                        style: TextStyle(
                          color: isDark ? AppColors.darkTextPrimary : AppColors.lightTextPrimary,
                        ),
                        decoration: const InputDecoration(
                          hintText: 'Message',
                          border: InputBorder.none,
                          contentPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                        ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 8),
                  GestureDetector(
                    onTapDown: (_) {
                      if (!_isTyping) _startRecording();
                    },
                    onTapUp: (_) {
                      if (!_isTyping) _stopRecording();
                    },
                    onTapCancel: () {
                      if (!_isTyping) _stopRecording();
                    },
                    child: Container(
                      decoration: BoxDecoration(
                        color: theme.colorScheme.primary,
                        shape: BoxShape.circle,
                      ),
                      child: IconButton(
                        icon: Icon(
                          _isTyping ? Icons.send : (_isRecording ? Icons.mic_none : Icons.mic),
                          color: Colors.white,
                        ),
                        onPressed: _isTyping ? () => _sendMessage() : null,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}
